/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Person_Information;
import Business.Checking_Account;
import javax.swing.JOptionPane;

/**
 *
 * @author nitya
 */
public class Create_CheckingAcct_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Create_CheckingAcct_Panel
     */
    private Person_Information person;
    public Create_CheckingAcct_Panel(Person_Information person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankAccNo = new javax.swing.JLabel();
        AccBalance = new javax.swing.JLabel();
        BankName_Txt = new javax.swing.JTextField();
        AccType_Txt = new javax.swing.JTextField();
        AcctType = new javax.swing.JLabel();
        CheckingInfo = new javax.swing.JLabel();
        AccNo_Txt = new javax.swing.JTextField();
        AcctBalance_Txt = new javax.swing.JTextField();
        Bank_Routing_No_Txt = new javax.swing.JTextField();
        BankName = new javax.swing.JLabel();
        BankRoutingNo = new javax.swing.JLabel();
        CreateBtn = new javax.swing.JButton();

        BankAccNo.setText("Bank Account No:");

        AccBalance.setText("Account Balance:");

        AcctType.setText("Account Type:");

        CheckingInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CheckingInfo.setText("Checking Account Information");

        BankName.setText("Bank Name:");

        BankRoutingNo.setText("Bank Routing No:");

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BankAccNo)
                                .addComponent(BankRoutingNo)
                                .addComponent(BankName))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AcctType)
                                .addComponent(AccBalance)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bank_Routing_No_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 282, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BankName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccNo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AcctBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(CheckingInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(CreateBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(CheckingInfo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankName)
                    .addComponent(BankName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankRoutingNo)
                    .addComponent(AccType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankAccNo)
                    .addComponent(AccNo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccBalance)
                    .addComponent(AcctBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bank_Routing_No_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcctType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(CreateBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        Checking_Account personCAccount = new Checking_Account();
        personCAccount.setBankName(BankName_Txt.getText());
        personCAccount.setBankRountingNo(Bank_Routing_No_Txt.getText());
        personCAccount.setBankAccNo(AccNo_Txt.getText());
        personCAccount.setAccBalance(AcctBalance_Txt.getText());
        personCAccount.setAccType(AccType_Txt.getText());
        person.setPersonChecking(personCAccount);
        JOptionPane.showMessageDialog(null,"Create Checking Account successfully" );        // TODO add your handling code here:
    }//GEN-LAST:event_CreateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccBalance;
    private javax.swing.JTextField AccNo_Txt;
    private javax.swing.JTextField AccType_Txt;
    private javax.swing.JTextField AcctBalance_Txt;
    private javax.swing.JLabel AcctType;
    private javax.swing.JLabel BankAccNo;
    private javax.swing.JLabel BankName;
    private javax.swing.JTextField BankName_Txt;
    private javax.swing.JLabel BankRoutingNo;
    private javax.swing.JTextField Bank_Routing_No_Txt;
    private javax.swing.JLabel CheckingInfo;
    private javax.swing.JButton CreateBtn;
    // End of variables declaration//GEN-END:variables
}
