/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person_Information;

/**
 *
 * @author nitya
 */
public class View_GeneralInfo_Panel extends javax.swing.JPanel {

    /**
     * Creates new form View_GeneralInfo_Panel
     */
    public View_GeneralInfo_Panel(Person_Information person) {
        initComponents();
        displayGeneralInfo(person);
    }
private void displayGeneralInfo(Person_Information person)
{
    String personFirstName=person.getPersonGeneral().getFirstName();
    FirstName_Txt.setText(personFirstName);
    
    String personLastName=person.getPersonGeneral().getLastName();
    LastName_Txt.setText(personLastName);
 
    String personPhno=person.getPersonGeneral().getPhoneNumber();
    PhoneNum_Txt.setText(personPhno);
    
    String personDOB=person.getPersonGeneral().getDateofBirth();
    DOB_Txt.setText(personDOB);
    
    String personAge=person.getPersonGeneral().getAge();
    Age_Txt.setText(personAge);
    
  
    String personHeight=person.getPersonGeneral().getHeight();
    Height_Txt.setText(personHeight);
    
    String personWeight=person.getPersonGeneral().getWeight();
    Weight_Txt.setText(personWeight);
    
    String personSSN=person.getPersonGeneral().getSSN();
    SSN_Txt.setText(personSSN);
    
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LastName_Txt = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        Weight_Txt = new javax.swing.JTextField();
        DemographicInfo = new javax.swing.JLabel();
        SSN_Txt = new javax.swing.JTextField();
        PhoneNum_Txt = new javax.swing.JTextField();
        Height = new javax.swing.JLabel();
        Age_Txt = new javax.swing.JTextField();
        Weight = new javax.swing.JLabel();
        DOB_Txt = new javax.swing.JTextField();
        SSN = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        Height_Txt = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        PhoneNum = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        FirstName_Txt = new javax.swing.JTextField();

        Age.setText("Age:");

        DemographicInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DemographicInfo.setText("Demographic Information");

        Height.setText("Height:");

        Age_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_TxtActionPerformed(evt);
            }
        });

        Weight.setText("Weight:");

        DOB_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB_TxtActionPerformed(evt);
            }
        });

        SSN.setText("SSN:");

        FirstName.setText("First Name:");

        LastName.setText("Last Name:");

        PhoneNum.setText("Phone Number:");

        DOB.setText("Date Of Birth:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstName)
                    .addComponent(LastName)
                    .addComponent(PhoneNum)
                    .addComponent(DOB)
                    .addComponent(Age))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Age_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOB_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNum_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Height)
                            .addComponent(Weight)
                            .addComponent(SSN))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SSN_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Weight_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Height_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(DemographicInfo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(DemographicInfo)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastName)
                            .addComponent(LastName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNum)
                            .addComponent(PhoneNum_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOB)
                            .addComponent(DOB_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Height)
                            .addComponent(Height_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Weight)
                            .addComponent(Weight_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSN)
                            .addComponent(SSN_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(Age_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Age_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TxtActionPerformed

    private void DOB_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_TxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JTextField Age_Txt;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOB_Txt;
    private javax.swing.JLabel DemographicInfo;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstName_Txt;
    private javax.swing.JLabel Height;
    private javax.swing.JTextField Height_Txt;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastName_Txt;
    private javax.swing.JLabel PhoneNum;
    private javax.swing.JTextField PhoneNum_Txt;
    private javax.swing.JLabel SSN;
    private javax.swing.JTextField SSN_Txt;
    private javax.swing.JLabel Weight;
    private javax.swing.JTextField Weight_Txt;
    // End of variables declaration//GEN-END:variables
}
