/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person_Information;
import Business.Address_Information;
import javax.swing.JOptionPane;


/**
 *
 * @author nitya
 */
public class Create_Adress_Panel extends javax.swing.JPanel {

    /**
     * Creates new form AdressPanel
     */
    private Person_Information person;
    public Create_Adress_Panel(Person_Information person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AdressInfo = new javax.swing.JLabel();
        StreetAddress = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        Zipcode = new javax.swing.JLabel();
        Streetaddress_Txt = new javax.swing.JTextField();
        State_Txt = new javax.swing.JTextField();
        Zipcode_Txt = new javax.swing.JTextField();
        City_Txt = new javax.swing.JTextField();
        CreateBtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        AdressInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdressInfo.setText("Address Information");

        StreetAddress.setText("Street Address:");

        City.setText("City:");

        State.setText("State:");

        Zipcode.setText("ZipCode:");

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(AdressInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StreetAddress)
                            .addComponent(City)
                            .addComponent(State)
                            .addComponent(Zipcode))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Zipcode_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(State_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Streetaddress_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(City_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(CreateBtn)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AdressInfo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StreetAddress)
                    .addComponent(Streetaddress_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City)
                    .addComponent(City_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State)
                    .addComponent(State_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zipcode)
                    .addComponent(Zipcode_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(CreateBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        
        Address_Information personAddress = new Address_Information();
        personAddress.setStreetAdress(Streetaddress_Txt.getText());
        personAddress.setCity(City_Txt.getText());
        personAddress.setState(State_Txt.getText());
        personAddress.setZipcode(Zipcode_Txt.getText());
        person.setPersonAdress(personAddress);
        JOptionPane.showMessageDialog(null,"Create Address successfully" );
               // TODO add your handling code here:
    }//GEN-LAST:event_CreateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdressInfo;
    private javax.swing.JLabel City;
    private javax.swing.JTextField City_Txt;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JLabel State;
    private javax.swing.JTextField State_Txt;
    private javax.swing.JLabel StreetAddress;
    private javax.swing.JTextField Streetaddress_Txt;
    private javax.swing.JLabel Zipcode;
    private javax.swing.JTextField Zipcode_Txt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
