/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Person_Information;
import Business.Medical_Information;
import javax.swing.JOptionPane;

/**
 *
 * @author nitya
 */
public class Create_MedicalInfo_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Create_MedicalInfo_Panel
     */
    private Person_Information person;
    public Create_MedicalInfo_Panel(Person_Information person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedicalInfo = new javax.swing.JLabel();
        Alergy2_Txt = new javax.swing.JTextField();
        Alergy3_Txt = new javax.swing.JTextField();
        Alergy1_Txt = new javax.swing.JTextField();
        MedicalRecordNo = new javax.swing.JLabel();
        Alergy1 = new javax.swing.JLabel();
        Alergy2 = new javax.swing.JLabel();
        Alergy3 = new javax.swing.JLabel();
        MedicalRecordNo_Txt = new javax.swing.JTextField();
        CreateBtn = new javax.swing.JButton();

        MedicalInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MedicalInfo.setText("Medical Information");

        MedicalRecordNo.setText("Medical Record Number:");

        Alergy1.setText("Alergy 1:");

        Alergy2.setText("Alergy 2:");

        Alergy3.setText("Alergy 3:");

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(CreateBtn)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(MedicalInfo))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MedicalRecordNo)
                                .addComponent(Alergy1)
                                .addComponent(Alergy2)
                                .addComponent(Alergy3))
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Alergy3_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Alergy2_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MedicalRecordNo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Alergy1_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(CreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(MedicalInfo)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MedicalRecordNo)
                        .addComponent(MedicalRecordNo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Alergy1)
                        .addComponent(Alergy1_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Alergy2)
                        .addComponent(Alergy2_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Alergy3)
                        .addComponent(Alergy3_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(57, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        Medical_Information MedicalInfo = new Medical_Information();
        MedicalInfo.setMedicalRecNo(MedicalRecordNo_Txt.getText());
        MedicalInfo.setAlergy1(Alergy1_Txt.getText());
        MedicalInfo.setAlergy2(Alergy2_Txt.getText());
        MedicalInfo.setAlergy3(Alergy3_Txt.getText());
        person.setPersonMedical(MedicalInfo);
        JOptionPane.showMessageDialog(null,"Create Medical successfully" );        // TODO add your handling code here:
    }//GEN-LAST:event_CreateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alergy1;
    private javax.swing.JTextField Alergy1_Txt;
    private javax.swing.JLabel Alergy2;
    private javax.swing.JTextField Alergy2_Txt;
    private javax.swing.JLabel Alergy3;
    private javax.swing.JTextField Alergy3_Txt;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JLabel MedicalInfo;
    private javax.swing.JLabel MedicalRecordNo;
    private javax.swing.JTextField MedicalRecordNo_Txt;
    // End of variables declaration//GEN-END:variables
}
