/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Person_Information;
import Business.Drivers_License;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Image;

/**
 *
 * @author nitya
 */
public class Create_DriverLicense_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Driver_License_Information
     */
    private Person_Information person;
    private Drivers_License personDriver;
    public Create_DriverLicense_Panel(Person_Information person) {
        initComponents();
        this.person=person;
        personDriver = new Drivers_License();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpiryDate = new javax.swing.JLabel();
        BloodType = new javax.swing.JLabel();
        LicenseNum_Txt = new javax.swing.JTextField();
        IssueDate_Txt = new javax.swing.JTextField();
        Picture = new javax.swing.JLabel();
        DriverLicense = new javax.swing.JLabel();
        ExpiryDate_Txt = new javax.swing.JTextField();
        LicenseNum = new javax.swing.JLabel();
        IssueDate = new javax.swing.JLabel();
        CreateBtn = new javax.swing.JButton();
        BloodType_Txt = new javax.swing.JTextField();
        Browse = new javax.swing.JButton();
        ImgeText_Field = new javax.swing.JTextField();

        ExpiryDate.setText("Date Of Expiry:");

        BloodType.setText("Blood Type:");

        Picture.setText("Picture");

        DriverLicense.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DriverLicense.setText("Driver License Information");

        LicenseNum.setText("License Number:");

        IssueDate.setText("Date Of Issue:");

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        Browse.setText("Browse");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Picture)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Browse)
                                .addGap(57, 57, 57)
                                .addComponent(ImgeText_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExpiryDate)
                                    .addComponent(IssueDate)
                                    .addComponent(LicenseNum))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BloodType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BloodType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 393, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LicenseNum_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IssueDate_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExpiryDate_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(DriverLicense))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(CreateBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(DriverLicense)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNum)
                    .addComponent(LicenseNum_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IssueDate)
                    .addComponent(IssueDate_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpiryDate)
                    .addComponent(ExpiryDate_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodType)
                    .addComponent(BloodType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Picture)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Browse)
                        .addComponent(ImgeText_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(CreateBtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
       Drivers_License Drivers_License = new Drivers_License();
        Drivers_License.setLicenseNo(LicenseNum_Txt.getText());
        Drivers_License.setDateofIssue(IssueDate_Txt.getText());
        Drivers_License.setDateofExpiration(ExpiryDate_Txt.getText());
        Drivers_License.setBloodtype(BloodType_Txt.getText());
        person.setPersonDL(Drivers_License);
        JOptionPane.showMessageDialog(null,"Create DL successfully" ); // TODO add your handling code here:
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
                                             
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImgeText_Field.setText(filename);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(Picture.getWidth(), Picture.getHeight(), Image.SCALE_SMOOTH));
        Picture.setIcon(imageIcon);
        personDriver.setPicture(filename);
        person.setPersonDL(personDriver);
        
               // TODO add your handling code here:
    }//GEN-LAST:event_BrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodType;
    private javax.swing.JTextField BloodType_Txt;
    private javax.swing.JButton Browse;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JLabel DriverLicense;
    private javax.swing.JLabel ExpiryDate;
    private javax.swing.JTextField ExpiryDate_Txt;
    private javax.swing.JTextField ImgeText_Field;
    private javax.swing.JLabel IssueDate;
    private javax.swing.JTextField IssueDate_Txt;
    private javax.swing.JLabel LicenseNum;
    private javax.swing.JTextField LicenseNum_Txt;
    private javax.swing.JLabel Picture;
    // End of variables declaration//GEN-END:variables
}
