/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person_Information;

/**
 *
 * @author nitya
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person_Information person;
    public MainJFrame() {
        initComponents();
        person=new Person_Information();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        General_Info_CreateBtn = new javax.swing.JButton();
        General_Info_ViewBtn = new javax.swing.JButton();
        General_Info = new javax.swing.JLabel();
        Address_Info = new javax.swing.JLabel();
        Address_Info_CreateBtn = new javax.swing.JButton();
        Address_Info_ViewBtn = new javax.swing.JButton();
        DL_Info = new javax.swing.JLabel();
        DL_Info_CreateBtn = new javax.swing.JButton();
        DL_Info_ViewBtn = new javax.swing.JButton();
        Saving_Acct_Info = new javax.swing.JLabel();
        Saving_Acct_Info_CreateBtn = new javax.swing.JButton();
        Saving_Acct_Info_ViewBtn = new javax.swing.JButton();
        Checking_Acct_Info = new javax.swing.JLabel();
        Checking_Acct_Info_CreateBtn = new javax.swing.JButton();
        Checking_Acct_Info_ViewBtn = new javax.swing.JButton();
        Medical_Info = new javax.swing.JLabel();
        Medical_Info_CreateBtn = new javax.swing.JButton();
        Medical_Info_ViewBtn = new javax.swing.JButton();
        Personal_Info = new javax.swing.JLabel();
        Personal_Info_Btn = new javax.swing.JButton();
        DisplayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        General_Info_CreateBtn.setText("Create");
        General_Info_CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                General_Info_CreateBtnActionPerformed(evt);
            }
        });

        General_Info_ViewBtn.setText("View");
        General_Info_ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                General_Info_ViewBtnActionPerformed(evt);
            }
        });

        General_Info.setText("General_Information");

        Address_Info.setText("Adress_Information");

        Address_Info_CreateBtn.setText("Create");
        Address_Info_CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_Info_CreateBtnActionPerformed(evt);
            }
        });

        Address_Info_ViewBtn.setText("View");
        Address_Info_ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_Info_ViewBtnActionPerformed(evt);
            }
        });

        DL_Info.setText("Drvier_License_Information");

        DL_Info_CreateBtn.setText("Create");
        DL_Info_CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DL_Info_CreateBtnActionPerformed(evt);
            }
        });

        DL_Info_ViewBtn.setText("View");
        DL_Info_ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DL_Info_ViewBtnActionPerformed(evt);
            }
        });

        Saving_Acct_Info.setText("Saving_Information");

        Saving_Acct_Info_CreateBtn.setText("Create");
        Saving_Acct_Info_CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saving_Acct_Info_CreateBtnActionPerformed(evt);
            }
        });

        Saving_Acct_Info_ViewBtn.setText("View");
        Saving_Acct_Info_ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saving_Acct_Info_ViewBtnActionPerformed(evt);
            }
        });

        Checking_Acct_Info.setText("Checking_Information");

        Checking_Acct_Info_CreateBtn.setText("Create");
        Checking_Acct_Info_CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checking_Acct_Info_CreateBtnActionPerformed(evt);
            }
        });

        Checking_Acct_Info_ViewBtn.setText("View");
        Checking_Acct_Info_ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checking_Acct_Info_ViewBtnActionPerformed(evt);
            }
        });

        Medical_Info.setText("Medical_Information");

        Medical_Info_CreateBtn.setText("Create");
        Medical_Info_CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Medical_Info_CreateBtnActionPerformed(evt);
            }
        });

        Medical_Info_ViewBtn.setText("View");
        Medical_Info_ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Medical_Info_ViewBtnActionPerformed(evt);
            }
        });

        Personal_Info.setText("Personal_Information");

        Personal_Info_Btn.setText("View");
        Personal_Info_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personal_Info_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Address_Info_CreateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(Address_Info_ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(General_Info_CreateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(General_Info_ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(General_Info))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Address_Info))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DL_Info_CreateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DL_Info_ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DL_Info))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Saving_Acct_Info_CreateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(Saving_Acct_Info_ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Saving_Acct_Info))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ControlJPanelLayout.createSequentialGroup()
                                .addComponent(Checking_Acct_Info_CreateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(Checking_Acct_Info_ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ControlJPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Checking_Acct_Info))))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ControlJPanelLayout.createSequentialGroup()
                                .addComponent(Medical_Info_CreateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(Medical_Info_ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ControlJPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Medical_Info))))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Personal_Info))
                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Personal_Info_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(General_Info)
                .addGap(18, 18, 18)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(General_Info_CreateBtn)
                    .addComponent(General_Info_ViewBtn))
                .addGap(26, 26, 26)
                .addComponent(Address_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Address_Info_CreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Address_Info_ViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(DL_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DL_Info_CreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DL_Info_ViewBtn))
                .addGap(18, 18, 18)
                .addComponent(Saving_Acct_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Saving_Acct_Info_CreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Saving_Acct_Info_ViewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Checking_Acct_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Checking_Acct_Info_CreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Checking_Acct_Info_ViewBtn))
                .addGap(18, 18, 18)
                .addComponent(Medical_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Medical_Info_CreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Medical_Info_ViewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Personal_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Personal_Info_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(ControlJPanel);

        javax.swing.GroupLayout DisplayJPanelLayout = new javax.swing.GroupLayout(DisplayJPanel);
        DisplayJPanel.setLayout(DisplayJPanelLayout);
        DisplayJPanelLayout.setHorizontalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        DisplayJPanelLayout.setVerticalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(DisplayJPanel);

        getContentPane().add(SplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void General_Info_CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_Info_CreateBtnActionPerformed
        Create_GeneralInfo_Panel createGeneralInfo=new Create_GeneralInfo_Panel(person);
     SplitPane.setRightComponent(createGeneralInfo);// TODO add your handling code here:
    }//GEN-LAST:event_General_Info_CreateBtnActionPerformed

    private void General_Info_ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_Info_ViewBtnActionPerformed
     View_GeneralInfo_Panel viewGenPanel= new View_GeneralInfo_Panel(person);
     SplitPane.setRightComponent(viewGenPanel); // TODO add your handling code here:
    }//GEN-LAST:event_General_Info_ViewBtnActionPerformed

    private void Address_Info_CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_Info_CreateBtnActionPerformed
       Create_Adress_Panel createAddressInfo=new Create_Adress_Panel(person);
     SplitPane.setRightComponent(createAddressInfo);  // TODO add your handling code here:
    }//GEN-LAST:event_Address_Info_CreateBtnActionPerformed

    private void Address_Info_ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_Info_ViewBtnActionPerformed
     View_Address_Panel viewAdressPanel= new View_Address_Panel(person);
     SplitPane.setRightComponent(viewAdressPanel);    // TODO add your handling code here:
    }//GEN-LAST:event_Address_Info_ViewBtnActionPerformed

    private void DL_Info_CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DL_Info_CreateBtnActionPerformed
      Create_DriverLicense_Panel createDLInfo=new Create_DriverLicense_Panel(person);
     SplitPane.setRightComponent(createDLInfo);   // TODO add your handling code here:
    }//GEN-LAST:event_DL_Info_CreateBtnActionPerformed

    private void DL_Info_ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DL_Info_ViewBtnActionPerformed
       View_DriverLicence_Panel viewDLPanel= new View_DriverLicence_Panel(person);
     SplitPane.setRightComponent(viewDLPanel);  // TODO add your handling code here:
    }//GEN-LAST:event_DL_Info_ViewBtnActionPerformed

    private void Saving_Acct_Info_CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saving_Acct_Info_CreateBtnActionPerformed
        Create_SavingAcct_Panel createSavingAcctInfo=new Create_SavingAcct_Panel(person);
     SplitPane.setRightComponent(createSavingAcctInfo); // TODO add your handling code here:
    }//GEN-LAST:event_Saving_Acct_Info_CreateBtnActionPerformed

    private void Saving_Acct_Info_ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saving_Acct_Info_ViewBtnActionPerformed
        View_SavingAcct_Panel viewSavingAcctPanel= new View_SavingAcct_Panel(person);
     SplitPane.setRightComponent(viewSavingAcctPanel); // TODO add your handling code here:
    }//GEN-LAST:event_Saving_Acct_Info_ViewBtnActionPerformed

    private void Checking_Acct_Info_CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Checking_Acct_Info_CreateBtnActionPerformed
       Create_CheckingAcct_Panel createCheckingAcctInfo=new Create_CheckingAcct_Panel(person);
     SplitPane.setRightComponent(createCheckingAcctInfo); // TODO add your handling code here:
    }//GEN-LAST:event_Checking_Acct_Info_CreateBtnActionPerformed

    private void Checking_Acct_Info_ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Checking_Acct_Info_ViewBtnActionPerformed
         View_CheckingAcct_Panel viewCheckingAcctPanel= new View_CheckingAcct_Panel(person);
     SplitPane.setRightComponent(viewCheckingAcctPanel); // TODO add your handling code here:
    }//GEN-LAST:event_Checking_Acct_Info_ViewBtnActionPerformed

    private void Medical_Info_CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Medical_Info_CreateBtnActionPerformed
       Create_MedicalInfo_Panel createMedicalInfo=new Create_MedicalInfo_Panel(person);
     SplitPane.setRightComponent(createMedicalInfo);   // TODO add your handling code here:
    }//GEN-LAST:event_Medical_Info_CreateBtnActionPerformed

    private void Medical_Info_ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Medical_Info_ViewBtnActionPerformed
       View_MedicalInfo_Panel ViewMedicalInfo=new View_MedicalInfo_Panel(person);
     SplitPane.setRightComponent(ViewMedicalInfo);  // TODO add your handling code here:
    }//GEN-LAST:event_Medical_Info_ViewBtnActionPerformed

    private void Personal_Info_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personal_Info_BtnActionPerformed
      View_PersonInfo_Panel_v2 ViewPersonInfo=new View_PersonInfo_Panel_v2(person);
     SplitPane.setRightComponent(ViewPersonInfo);  // TODO add your handling code here:
    }//GEN-LAST:event_Personal_Info_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Info;
    private javax.swing.JButton Address_Info_CreateBtn;
    private javax.swing.JButton Address_Info_ViewBtn;
    private javax.swing.JLabel Checking_Acct_Info;
    private javax.swing.JButton Checking_Acct_Info_CreateBtn;
    private javax.swing.JButton Checking_Acct_Info_ViewBtn;
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JLabel DL_Info;
    private javax.swing.JButton DL_Info_CreateBtn;
    private javax.swing.JButton DL_Info_ViewBtn;
    private javax.swing.JPanel DisplayJPanel;
    private javax.swing.JLabel General_Info;
    private javax.swing.JButton General_Info_CreateBtn;
    private javax.swing.JButton General_Info_ViewBtn;
    private javax.swing.JLabel Medical_Info;
    private javax.swing.JButton Medical_Info_CreateBtn;
    private javax.swing.JButton Medical_Info_ViewBtn;
    private javax.swing.JLabel Personal_Info;
    private javax.swing.JButton Personal_Info_Btn;
    private javax.swing.JLabel Saving_Acct_Info;
    private javax.swing.JButton Saving_Acct_Info_CreateBtn;
    private javax.swing.JButton Saving_Acct_Info_ViewBtn;
    private javax.swing.JSplitPane SplitPane;
    // End of variables declaration//GEN-END:variables
}
