/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person_Information;


/**
 *
 * @author nitya
 */
public class View_Address_Panel extends javax.swing.JPanel 
{

    /**
     * Creates new form View_Address_Panel
     */
    
   public View_Address_Panel(Person_Information person)
   {
        initComponents();
        displayadress(person);
   }

   private void displayadress(Person_Information person ) 
   {
       
   
   String personStAddress=person.getPersonAdress().getStreetAdress();
    Streetaddress_Txt.setText(personStAddress);
    
    String personCity=person.getPersonAdress().getCity();
    City_Txt.setText(personCity);
    
    String personState=person.getPersonAdress().getState();
    State_Txt.setText(personState);
    
    String personZipCode=person.getPersonAdress().getZipcode();
    Zipcode_Txt.setText(personZipCode);
    /**}
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdressInfo = new javax.swing.JLabel();
        State_Txt = new javax.swing.JTextField();
        Zipcode_Txt = new javax.swing.JTextField();
        City_Txt = new javax.swing.JTextField();
        StreetAddress = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        Zipcode = new javax.swing.JLabel();
        Streetaddress_Txt = new javax.swing.JTextField();

        AdressInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdressInfo.setText("Address Information");

        StreetAddress.setText("Street Address:");

        City.setText("City:");

        State.setText("State:");

        Zipcode.setText("ZipCode:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(AdressInfo))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StreetAddress)
                                .addComponent(City)
                                .addComponent(State)
                                .addComponent(Zipcode))
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Zipcode_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(State_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Streetaddress_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(City_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(AdressInfo)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StreetAddress)
                        .addComponent(Streetaddress_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(City)
                        .addComponent(City_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(State)
                        .addComponent(State_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Zipcode)
                        .addComponent(Zipcode_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdressInfo;
    private javax.swing.JLabel City;
    private javax.swing.JTextField City_Txt;
    private javax.swing.JLabel State;
    private javax.swing.JTextField State_Txt;
    private javax.swing.JLabel StreetAddress;
    private javax.swing.JTextField Streetaddress_Txt;
    private javax.swing.JLabel Zipcode;
    private javax.swing.JTextField Zipcode_Txt;
    // End of variables declaration//GEN-END:variables
}
