/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person_Information;

/**
 *
 * @author nitya
 */
public class View_CheckingAcct_Panel extends javax.swing.JPanel 
{

    /**
     * Creates new form View_Checking_Panel
     */
    public View_CheckingAcct_Panel(Person_Information person) 
    {
        initComponents();
        displayChecking(person);
    }

   private void displayChecking(Person_Information person ) 
   {
     String personCBankName=person.getPersonChecking().getBankName();
    BankCName_Txt.setText(personCBankName);
    
    String personCRoutingNO=person.getPersonChecking().getBankRountingNo();
    Bank_CRouting_No_Txt.setText(personCRoutingNO);
    
    String personCBankAcctNo=person.getPersonChecking().getBankAccNo();
    AccNo_CTxt.setText(personCBankAcctNo);
    
    String personCBankAccBal=person.getPersonChecking().getAccBalance();
    AcctCBalance_Txt.setText(personCBankAccBal);
    
    String personCBankAccType=person.getPersonChecking().getAccType();
    AccCType_Txt.setText(personCBankAccType);
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankCName_Txt = new javax.swing.JTextField();
        Bank_CRouting_No_Txt = new javax.swing.JTextField();
        AcctType = new javax.swing.JLabel();
        CheckingInfo = new javax.swing.JLabel();
        AccNo_CTxt = new javax.swing.JTextField();
        AcctCBalance_Txt = new javax.swing.JTextField();
        AccCType_Txt = new javax.swing.JTextField();
        BankName = new javax.swing.JLabel();
        BankRoutingNo = new javax.swing.JLabel();
        BankAccNo = new javax.swing.JLabel();
        AccBalance = new javax.swing.JLabel();

        AcctType.setText("Account Type:");

        CheckingInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CheckingInfo.setText("Checking Account Information");

        BankName.setText("Bank Name:");

        BankRoutingNo.setText("Bank Routing No:");

        BankAccNo.setText("Bank Account No:");

        AccBalance.setText("Account Balance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BankAccNo)
                                .addComponent(BankRoutingNo)
                                .addComponent(BankName))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AcctType)
                                .addComponent(AccBalance)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AccCType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckingInfo)
                            .addComponent(BankCName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bank_CRouting_No_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccNo_CTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AcctCBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(CheckingInfo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankName)
                    .addComponent(BankCName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankRoutingNo)
                    .addComponent(Bank_CRouting_No_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankAccNo)
                    .addComponent(AccNo_CTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccBalance)
                    .addComponent(AcctCBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccCType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcctType))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccBalance;
    private javax.swing.JTextField AccCType_Txt;
    private javax.swing.JTextField AccNo_CTxt;
    private javax.swing.JTextField AcctCBalance_Txt;
    private javax.swing.JLabel AcctType;
    private javax.swing.JLabel BankAccNo;
    private javax.swing.JTextField BankCName_Txt;
    private javax.swing.JLabel BankName;
    private javax.swing.JLabel BankRoutingNo;
    private javax.swing.JTextField Bank_CRouting_No_Txt;
    private javax.swing.JLabel CheckingInfo;
    // End of variables declaration//GEN-END:variables
}
