/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person_Information;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author nitya
 */
public class View_PersonInfo_Panel_v2 extends javax.swing.JPanel {

    /**
     * Creates new form View_PersonInfo_Panel
     */
    public View_PersonInfo_Panel_v2(Person_Information person) {
        initComponents();
        displayPersonInfo(person);
    }

    private void displayPersonInfo(Person_Information person)
    {
    String personFirstName=person.getPersonGeneral().getFirstName();
    FirstName_Txt.setText(personFirstName);
    
    String personLastName=person.getPersonGeneral().getLastName();
    LastName_Txt.setText(personLastName);
 
    String personPhno=person.getPersonGeneral().getPhoneNumber();
    PhoneNum_Txt.setText(personPhno);
    
    String personDOB=person.getPersonGeneral().getDateofBirth();
    DOB_Txt.setText(personDOB);
    
    String personAge=person.getPersonGeneral().getAge();
    Age_Txt.setText(personAge);
    
  
    String personHeight=person.getPersonGeneral().getHeight();
    Height_Txt.setText(personHeight);
    
    String personWeight=person.getPersonGeneral().getWeight();
    Weight_Txt.setText(personWeight);
    
    String personSSN=person.getPersonGeneral().getSSN();
    SSN_Txt.setText(personSSN);
    
    
   String personStAddress=person.getPersonAdress().getStreetAdress();
    Streetaddress_Txt.setText(personStAddress);
    
    String personCity=person.getPersonAdress().getCity();
    City_Txt.setText(personCity);
    
    String personState=person.getPersonAdress().getState();
    State_Txt.setText(personState);
    
    String personZipCode=person.getPersonAdress().getZipcode();
    Zipcode_Txt.setText(personZipCode);
    
    
    String personLicenseNO=person.getPersonDL().getLicenseNo();
    LicenseNum_Txt.setText(personLicenseNO);
        
    String personDLIssue=person.getPersonDL().getDateofIssue();
    IssueDate_Txt.setText(personDLIssue);
    
    String personDLExpiry=person.getPersonDL().getDateofExpiration();
    ExpiryDate_Txt.setText(personDLExpiry);
    
    String personBloodType=person.getPersonDL().getBloodtype();
    BloodType_Txt.setText(personBloodType);
        
    String PsersonImage = person.getPersonDL().getPicture();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(PsersonImage).getImage().getScaledInstance(150,150 , Image.SCALE_SMOOTH));
        Picture.setIcon(imageIcon);
        
    String personCBankName=person.getPersonChecking().getBankName();
    BankCName_Txt.setText(personCBankName);
    
    String personCRoutingNO=person.getPersonChecking().getBankRountingNo();
    Bank_CRouting_No_Txt.setText(personCRoutingNO);
    
    String personCBankAcctNo=person.getPersonChecking().getBankAccNo();
    AccNo_CTxt.setText(personCBankAcctNo);
    
    String personCBankAccBal=person.getPersonChecking().getAccBalance();
    AcctCBalance_Txt.setText(personCBankAccBal);
    
    String personCBankAccType=person.getPersonChecking().getAccType();
    AccCType_Txt.setText(personCBankAccType);
    
    String personSBankName=person.getPersonSaving().getBankName();
    BankSName_Txt.setText(personSBankName);
    
    String personSRoutingNO=person.getPersonSaving().getBankRountingNo();
    Bank_SRouting_No_Txt.setText(personSRoutingNO);
    
    String personSBankAcctNo=person.getPersonSaving().getBankAccNo();
    AccNo_STxt.setText(personSBankAcctNo);
    
    String personSBankAccBal=person.getPersonSaving().getAccBalance();
    AcctSBalance_Txt.setText(personSBankAccBal);
    
    String personSBankAccType=person.getPersonSaving().getAccType();
    AccSType_Txt.setText(personSBankAccType);
    
    String personMedRecNo=person.getPersonMedical().getMedicalRecNo();
    MedicalRecordNo_Txt.setText(personMedRecNo);
    
    String personAlergy1=person.getPersonMedical().getAlergy1();
    Alergy1_Txt.setText(personAlergy1);
    
     String personAlergy2=person.getPersonMedical().getAlergy2();
    Alergy2_Txt.setText(personAlergy2);
    
     String personAlergy3=person.getPersonMedical().getAlergy3();
    Alergy3_Txt.setText(personAlergy3);
    
    
       
    
    
    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SSN = new javax.swing.JLabel();
        FirstName_Txt = new javax.swing.JTextField();
        SavingBankName = new javax.swing.JLabel();
        AccNo_STxt = new javax.swing.JTextField();
        SavingAccountNo = new javax.swing.JLabel();
        SavingType = new javax.swing.JLabel();
        BankSName_Txt = new javax.swing.JTextField();
        SavingBalance = new javax.swing.JLabel();
        DateOfBirth = new javax.swing.JLabel();
        AcctSBalance_Txt = new javax.swing.JTextField();
        LastName_Txt = new javax.swing.JTextField();
        Bank_CRouting_No_Txt = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        CheckingRoutingNo = new javax.swing.JLabel();
        Age_Txt = new javax.swing.JTextField();
        AdressInformation = new javax.swing.JLabel();
        Zipcode_Txt = new javax.swing.JTextField();
        Zipcode = new javax.swing.JLabel();
        City_Txt = new javax.swing.JTextField();
        Street = new javax.swing.JLabel();
        State_Txt = new javax.swing.JTextField();
        CheckingBankName = new javax.swing.JLabel();
        AccNo_CTxt = new javax.swing.JTextField();
        CheckingAccountNO = new javax.swing.JLabel();
        CheckingType = new javax.swing.JLabel();
        BankCName_Txt = new javax.swing.JTextField();
        CheckingBalance = new javax.swing.JLabel();
        AcctCBalance_Txt = new javax.swing.JTextField();
        DeriverLicenseInformation = new javax.swing.JLabel();
        MedicalInformation = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        MedicalRecordNo = new javax.swing.JLabel();
        MedicalRecordNo_Txt = new javax.swing.JTextField();
        Alergy1 = new javax.swing.JLabel();
        Alergy1_Txt = new javax.swing.JTextField();
        Alergy2 = new javax.swing.JLabel();
        Alergy2_Txt = new javax.swing.JTextField();
        Alergy3 = new javax.swing.JLabel();
        Alergy3_Txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        State = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Streetaddress_Txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        SSN_Txt = new javax.swing.JTextField();
        Bank_SRouting_No_Txt = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        SavingRountingNo = new javax.swing.JLabel();
        DOB_Txt = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        PhoneNum_Txt = new javax.swing.JTextField();
        GeneralInformation = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Height = new javax.swing.JLabel();
        Height_Txt = new javax.swing.JTextField();
        Weight = new javax.swing.JLabel();
        Weight_Txt = new javax.swing.JTextField();
        LicenseNum_Txt = new javax.swing.JTextField();
        License_No = new javax.swing.JLabel();
        IssueDate_Txt = new javax.swing.JTextField();
        Issue_Date = new javax.swing.JLabel();
        ExpiryDate_Txt = new javax.swing.JTextField();
        Expiry_Date = new javax.swing.JLabel();
        BloodType_Txt = new javax.swing.JTextField();
        BloodType = new javax.swing.JLabel();
        BloodType1 = new javax.swing.JLabel();
        Picture = new javax.swing.JLabel();
        AccSType_Txt = new javax.swing.JTextField();
        AccCType_Txt = new javax.swing.JTextField();

        setAlignmentY(0.1F);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SSN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SSN.setText("SSN:");
        add(SSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));
        add(FirstName_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 88, 178, -1));

        SavingBankName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SavingBankName.setText("Bank Name:");
        add(SavingBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 315, -1, 22));
        add(AccNo_STxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 351, 221, -1));

        SavingAccountNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SavingAccountNo.setText("Account#:");
        add(SavingAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 353, -1, -1));

        SavingType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SavingType.setText("Type(Savings/checking):");
        add(SavingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 318, 163, -1));
        add(BankSName_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 316, 186, -1));

        SavingBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SavingBalance.setText("Balance:");
        add(SavingBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 318, -1, -1));

        DateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateOfBirth.setText("Date Of Birth(MM/DD/YYYY):");
        add(DateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 120, -1, -1));

        AcctSBalance_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcctSBalance_TxtActionPerformed(evt);
            }
        });
        add(AcctSBalance_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 316, 147, -1));
        add(LastName_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 88, 175, -1));

        Bank_CRouting_No_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bank_CRouting_No_TxtActionPerformed(evt);
            }
        });
        add(Bank_CRouting_No_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 433, 188, -1));

        Age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Age.setText("Age:");
        add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 117, -1, 22));

        CheckingRoutingNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckingRoutingNo.setText("Routing#:");
        add(CheckingRoutingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 435, -1, -1));
        add(Age_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 118, 53, -1));

        AdressInformation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AdressInformation.setText("2.Adress Information");
        add(AdressInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        Zipcode_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zipcode_TxtActionPerformed(evt);
            }
        });
        add(Zipcode_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 229, 188, -1));

        Zipcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Zipcode.setText("Zipcode:");
        add(Zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 231, -1, -1));
        add(City_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 229, 223, -1));

        Street.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Street.setText("Street:");
        add(Street, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 193, -1, 22));
        add(State_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 229, 163, -1));

        CheckingBankName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckingBankName.setText("Bank Name:");
        add(CheckingBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 397, -1, 22));
        add(AccNo_CTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 433, 221, -1));

        CheckingAccountNO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckingAccountNO.setText("Account#:");
        add(CheckingAccountNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 435, -1, -1));

        CheckingType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckingType.setText("Type(Savings/checking):");
        add(CheckingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 400, 163, -1));
        add(BankCName_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 398, 186, -1));

        CheckingBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckingBalance.setText("Balance:");
        add(CheckingBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 400, -1, -1));

        AcctCBalance_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcctCBalance_TxtActionPerformed(evt);
            }
        });
        add(AcctCBalance_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 398, 162, -1));

        DeriverLicenseInformation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DeriverLicenseInformation.setText("4.Driver's License Information");
        add(DeriverLicenseInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 479, -1, -1));

        MedicalInformation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MedicalInformation.setText("5.Medical Information");
        add(MedicalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 658, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 641, 952, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 462, 952, 10));

        MedicalRecordNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MedicalRecordNo.setText("Medical Record#:");
        add(MedicalRecordNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 687, -1, 22));
        add(MedicalRecordNo_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 688, 668, -1));

        Alergy1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alergy1.setText("Alergy 1:");
        add(Alergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 717, -1, 22));
        add(Alergy1_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 718, 211, -1));

        Alergy2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alergy2.setText("Alergy 2:");
        add(Alergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 717, -1, 22));
        add(Alergy2_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 718, 186, -1));

        Alergy3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alergy3.setText("Alergy 3:");
        add(Alergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 717, -1, 22));
        add(Alergy3_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 718, 186, -1));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 747, 952, -1));

        State.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        State.setText("State:");
        add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 231, -1, -1));

        City.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        City.setText("City:");
        add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 231, 41, -1));
        add(Streetaddress_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 194, 859, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 952, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 952, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 258, 952, 10));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("3.Bank Account Information");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 275, -1, -1));

        FirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstName.setText("First Name:");
        add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, 22));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 952, 10));

        SSN_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSN_TxtActionPerformed(evt);
            }
        });
        add(SSN_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 118, 89, -1));

        Bank_SRouting_No_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bank_SRouting_No_TxtActionPerformed(evt);
            }
        });
        add(Bank_SRouting_No_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 351, 188, -1));

        LastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LastName.setText("Last Name:");
        add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 90, 72, -1));

        SavingRountingNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SavingRountingNo.setText("Routing#:");
        add(SavingRountingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 353, -1, -1));

        DOB_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB_TxtActionPerformed(evt);
            }
        });
        add(DOB_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 118, 93, -1));

        PhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PhoneNumber.setText("Phone Number:");
        add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 90, -1, -1));
        add(PhoneNum_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 88, 157, -1));

        GeneralInformation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GeneralInformation.setText("1.General Information");
        add(GeneralInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Create a Personal Profile ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 6, -1, -1));

        Height.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Height.setText("Height:");
        add(Height, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 120, -1, -1));

        Height_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height_TxtActionPerformed(evt);
            }
        });
        add(Height_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 118, 89, -1));

        Weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Weight.setText("Weight:");
        add(Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 120, -1, -1));

        Weight_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Weight_TxtActionPerformed(evt);
            }
        });
        add(Weight_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 118, 89, -1));
        add(LicenseNum_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 531, 140, -1));

        License_No.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        License_No.setText("License No:");
        add(License_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 530, -1, 22));
        add(IssueDate_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 598, 107, -1));

        Issue_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Issue_Date.setText("Date Of Issue:");
        add(Issue_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 597, -1, 22));
        add(ExpiryDate_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 598, 106, -1));

        Expiry_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Expiry_Date.setText("Date Of Expiry:");
        add(Expiry_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 597, -1, 22));
        add(BloodType_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 598, 78, -1));

        BloodType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BloodType.setText("Blood Type:");
        add(BloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 597, -1, 22));

        BloodType1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BloodType1.setText("Picture:");
        add(BloodType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 495, -1, 22));

        Picture.setText("jLabel1");
        add(Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 479, 0, 104));
        add(AccSType_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 316, 101, -1));
        add(AccCType_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 398, 135, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AcctSBalance_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcctSBalance_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcctSBalance_TxtActionPerformed

    private void Bank_CRouting_No_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bank_CRouting_No_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bank_CRouting_No_TxtActionPerformed

    private void Zipcode_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zipcode_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Zipcode_TxtActionPerformed

    private void AcctCBalance_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcctCBalance_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcctCBalance_TxtActionPerformed

    private void Bank_SRouting_No_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bank_SRouting_No_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bank_SRouting_No_TxtActionPerformed

    private void DOB_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_TxtActionPerformed

    private void SSN_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSN_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSN_TxtActionPerformed

    private void Height_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Height_TxtActionPerformed

    private void Weight_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Weight_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Weight_TxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccCType_Txt;
    private javax.swing.JTextField AccNo_CTxt;
    private javax.swing.JTextField AccNo_STxt;
    private javax.swing.JTextField AccSType_Txt;
    private javax.swing.JTextField AcctCBalance_Txt;
    private javax.swing.JTextField AcctSBalance_Txt;
    private javax.swing.JLabel AdressInformation;
    private javax.swing.JLabel Age;
    private javax.swing.JTextField Age_Txt;
    private javax.swing.JLabel Alergy1;
    private javax.swing.JTextField Alergy1_Txt;
    private javax.swing.JLabel Alergy2;
    private javax.swing.JTextField Alergy2_Txt;
    private javax.swing.JLabel Alergy3;
    private javax.swing.JTextField Alergy3_Txt;
    private javax.swing.JTextField BankCName_Txt;
    private javax.swing.JTextField BankSName_Txt;
    private javax.swing.JTextField Bank_CRouting_No_Txt;
    private javax.swing.JTextField Bank_SRouting_No_Txt;
    private javax.swing.JLabel BloodType;
    private javax.swing.JLabel BloodType1;
    private javax.swing.JTextField BloodType_Txt;
    private javax.swing.JLabel CheckingAccountNO;
    private javax.swing.JLabel CheckingBalance;
    private javax.swing.JLabel CheckingBankName;
    private javax.swing.JLabel CheckingRoutingNo;
    private javax.swing.JLabel CheckingType;
    private javax.swing.JLabel City;
    private javax.swing.JTextField City_Txt;
    private javax.swing.JTextField DOB_Txt;
    private javax.swing.JLabel DateOfBirth;
    private javax.swing.JLabel DeriverLicenseInformation;
    private javax.swing.JTextField ExpiryDate_Txt;
    private javax.swing.JLabel Expiry_Date;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstName_Txt;
    private javax.swing.JLabel GeneralInformation;
    private javax.swing.JLabel Height;
    private javax.swing.JTextField Height_Txt;
    private javax.swing.JTextField IssueDate_Txt;
    private javax.swing.JLabel Issue_Date;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastName_Txt;
    private javax.swing.JTextField LicenseNum_Txt;
    private javax.swing.JLabel License_No;
    private javax.swing.JLabel MedicalInformation;
    private javax.swing.JLabel MedicalRecordNo;
    private javax.swing.JTextField MedicalRecordNo_Txt;
    private javax.swing.JTextField PhoneNum_Txt;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel Picture;
    private javax.swing.JLabel SSN;
    private javax.swing.JTextField SSN_Txt;
    private javax.swing.JLabel SavingAccountNo;
    private javax.swing.JLabel SavingBalance;
    private javax.swing.JLabel SavingBankName;
    private javax.swing.JLabel SavingRountingNo;
    private javax.swing.JLabel SavingType;
    private javax.swing.JLabel State;
    private javax.swing.JTextField State_Txt;
    private javax.swing.JLabel Street;
    private javax.swing.JTextField Streetaddress_Txt;
    private javax.swing.JLabel Weight;
    private javax.swing.JTextField Weight_Txt;
    private javax.swing.JLabel Zipcode;
    private javax.swing.JTextField Zipcode_Txt;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
