/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignsHist;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nitya
 */
public class AbnormalPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbnormalPanel
     */
    private VitalSignsHist vsh;
    private double maxBP;
    private double minBP;
  private void setFieldEnabled(boolean b) {
        txtTemperature.setEnabled(b);
        txtBloodPressure.setEnabled(b);
        txtPulse.setEnabled(b);
        txtDate.setEnabled(b);

    }
    public AbnormalPanel(VitalSignsHist vsh, double maxBP, double minBP) {

        initComponents();
        this.vsh = vsh;
        this.maxBP = maxBP;
        this.minBP = minBP;
        
        populatetheTable();

    }

    public void populatetheTable() {

        DefaultTableModel dtm = (DefaultTableModel) tableAbnormalVitalSigns.getModel();
        dtm.setRowCount(0);

        for (VitalSigns vs : vsh.getAbnormalList(maxBP, minBP)) {

            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getBloodPressure();
            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAbnormalVitalSigns = new javax.swing.JTable();
        txtTemperature = new javax.swing.JTextField();
        BloodPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        Pulse = new javax.swing.JLabel();
        txtPulse = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        Temp = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAbnormalVitalSigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "BloodPressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAbnormalVitalSigns);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 420, 140));

        txtTemperature.setEnabled(false);
        txtTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureActionPerformed(evt);
            }
        });
        add(txtTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 250, -1));

        BloodPressure.setText("Blood Pressure:");
        add(BloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 20));

        txtBloodPressure.setEnabled(false);
        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 250, -1));

        Pulse.setText("Pulse:");
        add(Pulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, 20));

        txtPulse.setEnabled(false);
        add(txtPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 250, -1));

        Date.setText("Date:");
        add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        txtDate.setEnabled(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 250, -1));

        Temp.setText("Temperature:");
        add(Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 20));

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        Heading.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Heading.setText("Abnormal Vital Signs");
        add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btnConfirm.setBackground(new java.awt.Color(153, 255, 102));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:

        int selectedRow = tableAbnormalVitalSigns.getSelectedRow();

        if (selectedRow >= 0) {
            VitalSigns vs = (VitalSigns) tableAbnormalVitalSigns.getValueAt(selectedRow, 0);
            txtBloodPressure.setText(String.valueOf(vs.getBloodPressure()));
            txtTemperature.setText(String.valueOf(vs.getTemperature()));
            txtPulse.setText(String.valueOf(vs.getPulse()));
            txtDate.setText(vs.getDate());

        } else {
            JOptionPane.showMessageDialog(null, "No row is selected");
        }

    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRow = tableAbnormalVitalSigns.getSelectedRow();

        if (selectedRow >= 0) {

            VitalSigns vs = (VitalSigns) tableAbnormalVitalSigns.getValueAt(selectedRow, 0);
            vsh.deleteVitals(vs);
            JOptionPane.showMessageDialog(null, "Record is Deleted");
            populatetheTable();

        } else {
            JOptionPane.showMessageDialog(null, "No row is selected");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
      

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPressure;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Pulse;
    private javax.swing.JLabel Temp;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAbnormalVitalSigns;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
