/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignsHist;
import Business.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author nitya
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
   
    private VitalSignsHist vsh;
    CreateVitalJPanel(VitalSignsHist vsh) {
        initComponents();
        this.vsh = vsh;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        BloodPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        Pulse = new javax.swing.JLabel();
        txtPulse = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        Temp = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Heading.setText("Add Vital Signs");
        add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        add(txtTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 119, 200, -1));

        BloodPressure.setText("Blood Pressure:");
        add(BloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, -1));

        Pulse.setText("Pulse:");
        add(Pulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        add(txtPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 200, -1));

        Date.setText("Date:");
        add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, -1));

        Temp.setText("Temperature:");
        add(Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        double temperature = Double.parseDouble(txtTemperature.getText());
        double bp = Double.parseDouble(txtBloodPressure.getText());
        int pulse = Integer.parseInt(txtPulse.getText());
        String date = txtDate.getText();
        
        VitalSigns v= vsh.addVitals();
        v.setTemperature(temperature);
        v.setBloodPressure(bp);
        v.setPulse(pulse);
        v.setDate(date);
        
        JOptionPane.showMessageDialog(null, "Vital Signs are added successfully!");
        txtTemperature.setText("");
        txtBloodPressure.setText("");
        txtPulse.setText("");
        txtDate.setText("");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPressure;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Pulse;
    private javax.swing.JLabel Temp;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
